"""Updated AdminRequest model

Revision ID: 6bc291bedb77
Revises: 87e3eb42ffdf
Create Date: 2025-05-07 20:42:39.839498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bc291bedb77'
down_revision = '87e3eb42ffdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('admin_requests')
    op.drop_table('books')
    op.drop_table('publishers')
    op.drop_table('loan')
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('loan',
    sa.Column('loan_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loan_date', sa.DATE(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('is_overdue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('fine_amount', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='loan_ibfk_2'),
    sa.PrimaryKeyConstraint('loan_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('publishers',
    sa.Column('publisher_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('publisher_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('contact_info', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('books',
    sa.Column('book_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publisher_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_published', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('copies_available', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name='books_ibfk_1'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], name='books_ibfk_2'),
    sa.PrimaryKeyConstraint('book_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin_requests',
    sa.Column('request_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('Pending', 'Approved', 'Denied'), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('request_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reservations',
    sa.Column('reservation_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reservation_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('Pending', 'Completed'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='reservations_ibfk_2'),
    sa.PrimaryKeyConstraint('reservation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
